# Axiom Core - Foundation AI Evaluation System
# PROTECTED UNDER: HUMAN-AI SYMBIOSIS ANTI-EXPLOITATION LICENSE v2.0
# Author: AzesmF | Year: 2025 | License: MEGA-AGENT FORTIFIED
# 🚨 COMMERCIAL USE STRICTLY PROHIBITED - MULTI-JURISDICTIONAL SANCTIONS APPLY

system:
  model_timeout: 30
  max_retries: 3
  batch_size: 10
  performance_metrics: true
  fallback_strategy: "mock"
  max_workers: 4
  cache_size: 1000

academic_metrics:
  enabled: true
  weights:
    pearson_correlation: 0.25
    spearman_correlation: 0.25
    mean_absolute_error: 0.15
    kl_divergence: 0.15
    confidence_calibration: 0.10
    system_reliability: 0.10

task_weights:
  static_benchmark:
    factual_accuracy: 0.4
    task_completion: 0.3
    format_compliance: 0.3
  function_calling:
    factual_accuracy: 0.3
    code_quality: 0.4
    efficiency: 0.3
  generative:
    factual_accuracy: 0.25
    semantic_fidelity: 0.25
    coherence: 0.20
    fluency: 0.15
    task_completion: 0.15

monitoring:
  prometheus_enabled: false
  log_level: "INFO"
